group: edge
sudo: required
language: bash
services: docker

before_install:
  - docker network create -d bridge rijanet
  - docker run -d --name rijamysql --net=rijanet --env MYSQL_ROOT_PASSWORD=changemeroot --env MYSQL_DATABASE=wordpress --env MYSQL_USER=wordpress --env MYSQL_PASSWORD=changemeuser mysql:5.5.45

script:
  - docker build -t rija/docker-nginx-fpm-caches-wordpress .
  - docker run --privileged -d --name rijaweb --net=rijanet --env SERVER_NAME=dockerfiletest.cinecinetique.com --env DB_HOSTNAME=rijamysql --env DB_USER=wordpress --env DB_PASSWORD=changemeuser --env DB_DATABASE=wordpress -v /etc/letsencrypt:/etc/letsencrypt -p 443:443 -p 80:80 rija/docker-nginx-fpm-caches-wordpress
  - docker exec -it rijaweb bash -c "cd /letsencrypt/ && ./letsencrypt-auto certonly --help"
  - docker exec -it rijaweb bash -c "cat /etc/hosts"
  - docker exec -it rijaweb bash -c "cat /etc/letsencrypt/cli.ini"
  - docker exec -it rijaweb bash -c "cat /usr/share/nginx/www/wp-config.php"
  - docker exec -it rijaweb bash -c "ps -e"
  - docker exec -it rijaweb bash -c "ps -e" | grep "supervisor"
  - docker exec -it rijaweb bash -c "ps -e" | grep "nginx"
  - docker exec -it rijaweb bash -c "ps -e" | grep "php5-fpm"
  - docker exec -it rijaweb bash -c "ps -e" | grep "cron"
  - docker exec -it rijaweb bash -c "curl --head http://dockerfiletest.cinecinetique.com"
