language: bash
services: docker

before_install:
  - docker network create -d bridge rijanet
  - docker run -d --name rijamysql --net=rijanet --env MYSQL_ROOT_PASSWORD=changemeroot --env MYSQL_DATABASE=wordpress --env MYSQL_USER=wordpress --env MYSQL_PASSWORD=changemeuser mysql:5.5.45

script:
  - docker build -t rija/docker-nginx-fpm-caches-wordpress .
  - docker run -d --name rijaweb --net=rijanet --env SERVER_NAME=dockerfiletest.cinecinetique.com --env DB_HOSTNAME=rijamysql --env DB_USER=wordpress --env DB_PASSWORD=changemeuser --env DB_DATABASE=wordpress -v /etc/letsencrypt:/etc/letsencrypt -p 443:443 -p 80:80 rija/docker-nginx-fpm-caches-wordpress
  - docker exec -it rijaweb bash -c "ps -ef" | grep nginx
  - docker exec -it rijaweb bash -c "ps -ef" | grep php-fpm
  - docker exec -it rijaweb bash -c "ps -ef" | grep cron
  - docker exec -it rijaweb bash -c "ps -ef" | grep supervisor
  - docker exec -it rijaweb bash -c "cd /letsencrypt/ && ./letsencrypt-auto certonly --help"