language: bash
services: docker

before_install:
  - docker run -d --name rijamysql --net=rijanet --env MYSQL_ROOT_PASSWORD=changemeroot --env MYSQL_DATABASE=wordpress --env MYSQL_USER=wordpress --env MYSQL_PASSWORD=changemeuser mysql:5.5.45

script:
  - docker build -t rija/docker-nginx-fpm-caches-wordpress .