language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - docker

before_install:
  - docker run -d --name rijamysql --net=rijanet \
  	--env MYSQL_ROOT_PASSWORD=changemeroot \
  	--env MYSQL_DATABASE=wordpress \
  	--env MYSQL_USER=wordpress \
  	--env MYSQL_PASSWORD=changemeuser mysql:5.5.45

before_script:
  - docker build -t rija/docker-nginx-fpm-caches-wordpress .
  - docker run -d \
    --name rijaweb \
    --net=rijanet \
    --env SERVER_NAME=dockerfiletest.cinecinetique.com \
    --env DB_HOSTNAME=rijamysql \
    --env DB_USER=wordpress \
    --env DB_PASSWORD=changemeuser \
    --env DB_DATABASE=wordpress \
    -v /etc/letsencrypt:/etc/letsencrypt \
    -p 443:443 -p 80:80 \
    rija/docker-nginx-fpm-caches-wordpress

script:
 - docker exec -it rijaweb bash -c 'curl --head http://dockerfiletest.cinecinetique.com' | grep 301

