version: '2'
services:
  web:
    networks:
      - wp_net
    image: rija/docker-nginx-fpm-caches-wordpress
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    environment:
      SERVER_NAME:
      DB_HOSTNAME: dbs
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    links:
      - database:dbs
  database:
    networks:
      - wp_net
    image: mariadb:latest
    volumes_from:
      - dbdata
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  dbdata:
    volumes:
      - /var/lib/mysql
    image: mariadb:latest
networks:
  wp_net:
    driver: bridge
