version: '2'
services:
  web:
    networks:
      - wp_net
    image: rija/docker-nginx-fpm-caches-wordpress
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    environment:
      SERVER_NAME:
      LE_EMAIL:
      DB_HOSTNAME: dbs
      DB_USER: ${WP_DB_USER}
      DB_PASSWORD: ${WP_DB_PASSWORD}
      DB_DATABASE: ${WP_DB_NAME}
    links:
      - database:dbs
  database:
    networks:
      - wp_net
    image: mariadb:10.1.16
    volumes_from:
      - dbdata
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
  dbdata:
    volumes:
      - /var/lib/mysql
    image: mariadb:10.1.16
networks:
  wp_net:
    driver: bridge
