version: '2'
services:
  web:
    build:
      context: .
      args:
        GIT_SSH_URL: ${GIT_SSH_URL}
    environment:
      DEBUG: 'true'
      GIT_DEPLOY_KEY: 'git_deploy_key'
    image: ${IMAGE_NAME}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /${HOME}/.ssh:/root/deploykeys:ro
