#!/bin/bash

# Download Wordpress

WP_URL=https://wordpress.org/wordpress-${WP_VERSION}.tar.gz

if [[ $WP_VANILLA && ! $GIT_SSH_URL ]]; then

  cd /usr/share/nginx/ \
      && curl -o wp.tar.gz ${WP_URL} \
      && SELECTED_VERSION_CHECKSUM=${WP_HASH} \
      && echo $WP_VERSION \
      && echo $WP_HASH \
      && test `openssl sha1 wp.tar.gz | cut -d"=" -f2` = ${WP_HASH} \
      && tar -xvf wp.tar.gz \
      && rm wp.tar.gz
fi
